### PR TITLE
Bump req to 0.4.0

### PR DESCRIPTION
**Pull request by jwthomp**
Updating project to use newer req versions 0.4.x so the package will work with other common dependencies such as `swoosh` which require req 0.4.x.

What was done in this MR:
- Update project version from 0.1.2 to 0.1.3
- Update req dependency from 0.3.0 to 0.4.0
- Updated lock file
- Updated CHANGELOG.md file to reflect new version and changes

Tested locally before creating MR with `mix test`

### CODE REVIEW

**Comment by jwthomp** [comment]
Tested in another app by pulling the package in directly from my branch and am seeing the following error:

```
❯ mix changelog
==> changelog
Compiling 5 files (.ex)
Generated changelog app
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a binary

    (stdlib 5.2) :binary.match(["application/vnd.hex+erlang; charset=utf-8"], "application/vnd.hex+erlang")
    (hex_core 0.8.4) /Users/jwthomp/repos/github.com/jwthomp/they/deps/hex_core/src/hex_api.erl:104: :hex_api.request/4
    (changelog 0.1.3) lib/changelog/cli.ex:84: anonymous fn/3 in Changelog.CLI.fetch_changelogs/1
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (changelog 0.1.3) lib/changelog/cli.ex:83: Changelog.CLI.fetch_changelogs/1
    (changelog 0.1.3) lib/changelog/cli.ex:27: Changelog.CLI.run/1
    (mix 1.16.0) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.0) lib/mix/cli.ex:96: Mix.CLI.run_task/2
```

I'll need to investigate.

**Comment by jwthomp** [comment]
Fixed the header issue, but now when I run `mix changelog` in another repo I get:

```
** (UndefinedFunctionError) function Hex.Mix.packages_from_lock/1 is undefined (module Hex.Mix is not available)
    (hex 2.0.6) Hex.Mix.packages_from_lock(%{floki: {:hex, :floki, "0.35.2"
    ...
    (changelog 0.1.3) lib/changelog/cli.ex:23: Changelog.CLI.run/1
    (mix 1.16.0) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.0) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /Users/jwthomp/.asdf/installs/elixir/1.16.0/bin/mix:2: (file)
 ```
 
 Pulled in via mix.exs deps with:
 ```
       {:changelog, git: "git@github.com:jwthomp-fork/changelog.git", branch: "Bump_req_to_0.4.0"},
```

**Comment by jwthomp** [comment]
Fails first time, runs just fine second time.

So this appears to just be an issue where `mix changelog` will not work until after a `mix deps.compile` happens. Doing a `mix changelog` triggers the compile, but you don't see it work until you run it again.

However, if you do:
```
mix deps.clean --all ## To simulate fresh repo
mix deps.get
mix deps.compile
mix changelog
```

Then everything works fine.

**Comment by abshierjoel** [comment]
@jwthomp @zorbash 
For what it's worth, I tested this branch locally and it's working on a couple of my repos.

**Pull request merged**
